Fix progress page max_score scoring issue
Stanford-Online/xblock-free-text-response pull request #12
Opened 2017-02-08 00:56 UTC by caseylitton

max_score function needs to be included in
xblocks so the LMS progress page correctly
reports the progress for a subsection. Not
fixing this is confusing to the student and
could result in grading errors.

@kluo @stvstnfrd PR for fixing progress issue by adding max_score function to xblock.

https://trello.com/c/PqrXDAYi/669-graded-xblocks-not-correctly-reflected-in-grading

2017-02-09 20:06 UTC, kluo requested changes

2017-02-09 20:06 UTC, kluo commented on freetextresponse/freetextresponse.py
> +        return self.weight if self.has_score else None
Shouldn't this always return the _raw_ max score, `Credit.full.value`? The `has_score` attribute is defaulted to True so the boolean check is superfluous.

2017-02-09 20:56 UTC, caseylitton commented on freetextresponse/freetextresponse.py
> +        return self.weight if self.has_score else None
Based on other CAPA xblocks and their progress page, this should return the instructor weight.  Credit.full.value is always one.  If the weight is 3 for an xblock then the progress page available points goes up by 3 for that subsection.  

Per discussion, I'll update so max_score returns self.weight with no checks.

2017-02-09 21:30 UTC, stvstnfrd commented
This seems reasonable, +1

2017-02-10 01:26 UTC, kluo commented
+1

2017-02-13 23:29 UTC, merged