Add try ... except
Stanford-Online/xblock-free-text-response pull request #19
Opened 2017-07-21 19:53 UTC by jlikhuva

Added code to catch – and ignore – The
IntegrityError exception. Created a new
unit test that mocks the exception
in question to ensure that it is
gracefully ignored.

@caseylitton  @potsui @jspayd

2017-07-21 21:01 UTC, caseylitton requested changes

2017-07-21 21:01 UTC, caseylitton commented on freetextresponse/tests.py
> +    @ddt.data(Credit.zero, Credit.half, Credit.full)
We should not need to run this test for each type of credit to verify the exception is handled properly.   We still need to mock determine_credit however, so just use any one of the credit values.

2017-07-21 21:01 UTC, caseylitton commented on freetextresponse/tests.py
> +    def test_compute_score_error(self, credit):
Error is pretty vague.  Let's make the function name more specific, like  test_compute_score_integrity_error

2017-07-21 21:01 UTC, caseylitton commented on freetextresponse/tests.py
> +        Tests _compute_score's error handling
Same here too, let's use IntegrityError in the first line of the comment.  And be specific in the other parts of the comment as well. 

Does this test actually test that all exceptions are handle?  Or is it just the one IntegrityError?

2017-07-21 21:04 UTC, caseylitton commented
After you get two plus ones, you'll need to fix the commit message, 'Add try ... except'.  Your message needs to be less have 50 characters.  I assume that is where the '...' comes from

2017-07-21 21:27 UTC, jlikhuva commented on freetextresponse/tests.py
> +        Tests _compute_score's error handling
The current test only checks for the IntegrityError exception. The try - except that I introduced also only handles the IntegrityError exception. I could have it catch and ignore all exceptions, but I don't know if that is a good idea.

2017-07-21 22:03 UTC, stvstnfrd commented on freetextresponse/tests.py
> +        Tests _compute_score's error handling
@jlikhuva Yeah, I think that's what @caseylitton is pointing out; the comment implies that this handles more than it actually does. We should only be catching that specific exception in this case; let's update the docs to reflect what we're catching.

2017-07-21 22:04 UTC, stvstnfrd commented
@caseylitton The ellipsis may be coming from a lack of an empty line between the "subject" and "body"?

2017-07-21 22:15 UTC, caseylitton commented on freetextresponse/tests.py
> +        Tests _compute_score's error handling
Yes, thanks stv.  

@jlikhuva Specify exactly what's happening in the function.  We're forcing runtime.publish to throw an IntegrityError in order to test that compute_score passes it without issue.

2017-07-21 23:57 UTC, jlikhuva commented
@caseylitton @stvstnfrd  Fleshed out the documentation of the unit test. Also fixed the first commit message.

2017-07-24 21:45 UTC, caseylitton requested changes
Looks good.  Just remove unneeded ddt on your test.  

See if @caesar2164 can review before you push any more changes back up.  You can probably squash before the next push if he doesn't flag a major issue.

2017-07-24 21:45 UTC, caseylitton commented on freetextresponse/tests.py
> +    @ddt.data(Credit.zero)
Remove ddt entirely from this function.  We only need ddt when we want to run the same test with different parameters. 

In this case, we only need to use one credit value so...

return_value=credit   <---- Just set return_value to Credit.zero.  

Don't forget to remove credit from the function args.

2017-07-25 17:41 UTC, caesar2164 requested changes

2017-07-25 17:41 UTC, caesar2164 commented on freetextresponse/tests.py
> +    def test_compute_score_integrity_error(self, credit):
as @caseylitton said just remove the credit var being passed here.

2017-07-25 17:41 UTC, caesar2164 commented on freetextresponse/tests.py
> +        self.xblock._determine_credit = MagicMock(return_value=credit)
and just give this MagickMock `return_value=Credit.zero`

2017-07-25 19:04 UTC, jlikhuva commented
@caesar2164 @caesar2164 

Fixed the ddt issue and Squashed commits.

2017-07-25 20:54 UTC, caesar2164 approved these changes
Perfect! 👍

2017-07-25 20:56 UTC, caseylitton approved these changes

2017-07-25 20:56 UTC, caseylitton commented
+ 1

2017-07-25 22:39 UTC, merged

2017-07-26 03:39 UTC, stvstnfrd commented
@jlikhuva Next time around, you'll want to clean up the commit message when squashing. Many of the old messages (e.g. `Fix Pylint error.`) are no longer relevant. Looking at the code as it exists on disk and the new, post-squash git commit history, there _technically_ never _was_ a Pylint error ;)
That's a development artifact that's we've (intentionally) erased from history/existence.
So you don't need to (and shouldn't) mention it in the final commit message.