Move cached data from body to seq_content
Stanford-Online/xblock-free-text-response pull request #21
Opened 2017-07-26 21:18 UTC by potsui

@stvstnfrd @caesar2164 PR

Previously, some future update or rogue script could easily tamper with
our cached data attributes on the body element. We moved these data
attributes to be slightly less widely accessible.

Arising from conversation in previous [PR](https://github.com/Stanford-Online/xblock-free-text-response/pull/18)
[Trello](https://trello.com/c/IHM9cBHS/953-move-cached-data-from-body-element-to-their-own-element-for-ftr-xblock)

CC: @jlikhuva @jspayd

2017-07-26 21:21 UTC, caesar2164 approved these changes
Looks good to me. (Granted I helped you write this... 😁 ) 👍

2017-07-26 21:46 UTC, stvstnfrd commented on freetextresponse/private/view.js
> +    var $seq_content = $('#seq_content');
We should give this a more generalized name.
One of the benefits to having a variable here is that we could update the selector if we want to store this elsewhere in the future.
In this case, if we updated the selector, the variable name would no longer make sense,
so we'd technically want to update it too.

Maybe `container` or something?
That's not a great name; any better ideas?

2017-07-26 21:47 UTC, stvstnfrd requested changes
Code seems good, but we should chose a better variable name.

2017-07-27 00:01 UTC, potsui commented on freetextresponse/private/view.js
> +    var $seq_content = $('#seq_content');
`xblocksWrapper`? `contentContainer`? `xblocksContainer`? ¯\_(ツ)_/¯

2017-07-27 00:03 UTC, potsui commented
On a related note, since this fix was originally taken from the submit and compare block, I've started a branch locally making the same fix for that xblock. Does that sound good?

2017-08-03 19:28 UTC, stvstnfrd commented on freetextresponse/private/view.js
> +    var $seq_content = $('#seq_content');
`xblocksContainer` seems reasonable.

2017-08-04 05:09 UTC, stvstnfrd approved these changes

2017-08-04 05:12 UTC, stvstnfrd commented
Go ahead and squash the commits and we'll merge then put this on stage tomorrow.

2017-08-04 16:52 UTC, caesar2164 requested changes
Please bump version for this xblock, like this commit does: https://github.com/Stanford-Online/xblock-free-text-response/commit/ec5a21efd3357023b7b356cd1fefcccc3863d5e4

2017-08-04 18:06 UTC, caesar2164 approved these changes

2017-08-04 18:11 UTC, merged